import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Kumbh_Sans } from "next/font/google";

const kumbhsans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={kumbhsans.className}>
            <Navbar />
          {children}
        </body>
      </html>
  );
}
