"use client";
import React from "react";
import { motion } from "framer-motion"; // Import motion from Framer Motion
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Contact, Info, Medal, Navigation,} from "lucide-react";
import { DollarSign, BookOpen} from "lucide-react";
import {
  Chart as ChartJS,
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement,
  ArcElement,
  Tooltip,
  Legend,
} from "chart.js";
import { Doughnut } from "react-chartjs-2";

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement
);

const page = () => {
  // Define a common animation configuration
  const animationConfig = {
    initial: { opacity: 0, scale: 0.5 },
    animate: { opacity: 1, scale: 1, transition: { duration: 0.75 } }, // Increase duration for slower animation
    exit: { opacity: 0, scale: 0.5, transition: { duration: 0.75 } }, // Increase duration for slower animation
  };

  const data = {
    labels: ["Succesful", "Unsuccesful"],
    datasets: [
      {
        data: [60, 40], //
        backgroundColor: ["#F19B60", "#6088F1"],
        borderColor: ["", ""],
      },
    ],
  };

  const options = {
    legend: {
      labels: {
        fontColor: "white",
      }
    }
  }

  return (
    <div>
      <div className="flex items-center justify-center mr-4 ml-4 mt-4">
        <motion.div
          className="border border-gray-200 bg-black w-1/2 hover:bg-gray-900"
          {...animationConfig}
        >
          <CardHeader>
            <div className="flex items-center justify-between">
              <h1 className="font-semilight text-lg mr-2">Company Details</h1>
              <Info />
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-white text-2xl font-bold">
              Shreedhar Industries
            </p>
            <p className="text-gray-400 mt-2">Founder: Shreedhar Raj</p>
            <p className="text-gray-400 mt-2">New Delhi, India</p>
          </CardContent>
        </motion.div>

        <motion.div
          className="border border-gray-200 ml-4 bg-black w-1/2 hover:bg-gray-900"
          {...animationConfig}
        >
          <CardHeader>
            <div className="flex items-center justify-between">
              <h1 className="font-semilight text-lg mr-2">Contact Details</h1>
              <Contact />
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-white text-2xl font-bold">Shreedhar Raj</p>
            <p className="text-gray-400 mt-2">itsshreedharraj@gmail.com</p>
            <p className="text-gray-400 mt-2">The Shri Ram School Moulsari</p>
          </CardContent>
        </motion.div>

        <motion.div
          className="border border-gray-200 ml-4 bg-black w-1/2 hover:bg-gray-900"
          {...animationConfig}
        >
          <CardHeader>
            <div className="flex items-center justify-between">
              <h1 className="font-semilight text-lg mr-2">Business Details</h1>
              <Contact />
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-white text-2xl font-bold">Educify</p>
            <p className="text-gray-400 mt-2">Valuation of 10000 USD</p>
            <p className="text-gray-400 mt-2">10% growth rate</p>
          </CardContent>
        </motion.div>
      </div>
      <div className="flex items-center justify-center mt-4">
          <div className="w-1/4 mx-auto mt-4">
                <Doughnut data={data} options={options}/>
          </div>
        <motion.div className="border border-white mr-8 w-[700px] h-[400px] hover:bg-gray-900" {...animationConfig}>
          <h1 className="font-semilight text-lg font-semibold ml-4 mt-5">Prediction</h1>
          <h1 className="font-light text-lg text-gray-400 px-4">Generated by our ML Algorithm</h1>
          <div className="flex items-center justify-start ml-4 mt-4">
            <DollarSign/>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-transparent text-xl font-semibold px-2 mt-1">Predicted: </h1>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-white mt-1">1000000</h1>
          </div>
          <div className="flex items-center justify-start ml-4 mt-2">
            <BookOpen/>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-transparent text-xl font-semibold px-2 mt-1">Profitable: </h1>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-white mt-1">Yes</h1>
          </div>
          <div className="flex items-center justify-start ml-4 mt-2">
            <Medal/>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-transparent text-xl font-semibold px-2 mt-1">Chances of Success: </h1>
            <h1 className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-white mt-1">Medium</h1>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default page;
